### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by utapyngo** [pytest-dev/pytest-metadata#29] opened 2020-07-29 08:29 UTC
I am randomly (sometimes) getting the following error when running tests using a self-hosted GitHub Actions runner:

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/site-packages/_pytest/main.py", line 187, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/site-packages/_pytest/config/__init__.py", line 820, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/site-packages/pluggy/hooks.py", line 308, in call_historic
INTERNALERROR>     res = self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/site-packages/pytest_metadata/plugin.py", line 84, in pytest_configure
INTERNALERROR>     if name.startswith("pytest-"):
INTERNALERROR> AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by BeyondEvil** [comment] 2020-11-25 09:49
Sorry that I've missed this! @utapyngo 

Anymore information you can provide? Since it's intermittent it's extremely difficult to troubleshoot on my end.

**Comment by vineethchowdhary** [comment] 2021-08-31 10:15
Hi @BeyondEvil 

we are also seeing this issue, any update on it?

**Comment by BeyondEvil** [comment] 2021-08-31 22:14
> Hi @BeyondEvil
> 
> we are also seeing this issue, any update on it?

Sorry no, not until I get some more information (preferably a repo setup to reproduce). I don't have a way of troubleshooting things on self-hosted GHA runners.

**Comment by vineethchowdhary** [comment] 2021-09-02 06:00
this issue is intermittent. i also dont know the root cause.
I will add more details once i found any 

Thanks
Vineeth

**Comment by BeyondEvil** [comment] 2022-03-22 08:11
Closing this for now. Feel free to reopen if there's a way to consistently reproduce.

**Closed by BeyondEvil** 2022-03-22 08:11 UTC
Labels: needs more info
