### ISSUE TITLE
Environment table not showing on html report anymore

### ISSUE THREAD

**Issue by joancarrio-analog** [pytest-dev/pytest-metadata#71] opened 2023-05-29 10:42 UTC
Since 3.0.0 I could not see the metadata table in the html report, even though without accessing any of the hooks.
There might be a problem with the metadata and I don't know if it could be related with the issue of '_metadata' object not being acessed.

Thanks,
Joan.

**Comment by BeyondEvil** [comment] 2023-05-29 17:51
Closing this as a duplicate of: https://github.com/pytest-dev/pytest-html/issues/683

**Closed by BeyondEvil** 2023-05-29 17:51 UTC
